import transformers
from .autoround_quantizer import AutoHfQuantizer

transformers.quantizers.auto.AutoHfQuantizer = AutoHfQuantizer
transformers.quantizers.auto.AutoQuantizationConfig = AutoHfQuantizer
transformers.modeling_utils.AutoHfQuantizer = AutoHfQuantizer
from transformers import AutoModelForCausalLM as AutoRoundModelForCausalLM
from .export_to_autoround import save_quantized_as_autoround
