name: Feature Request
description: Suggest a new feature or improvement for AutoRound
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the following sections to help us understand your request.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a clear and detailed description of the feature you'd like to see.
      placeholder: Describe the feature and how it would work.
    validations:
      required: true
  
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Explain the motivation behind this feature request and provide use cases.
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered.
    validations:
      required: false
  
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Define the criteria that determine when this feature is complete. What needs to be implemented, tested, or documented?
      placeholder: |
        - [ ] Feature implemented and working as described
        - [ ] Unit tests added/updated
        - [ ] Documentation updated
        - [ ] Performance impact assessed
        - [ ] Example usage provided
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful
    validations:
      required: false
