file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/generated/sdpa)
set(SDPA_DECLARATIONS_FILE ${CMAKE_CURRENT_BINARY_DIR}/generated/sdpa/sdpa_kernel_declarations.hpp)

function(generate_sdpa_instantiation mode dtype_name dtype_type head_dim variant_name causal_value has_mask_value
         is_varlen_value)
  set(function_name launch_${mode}_kernel_${dtype_name}_${head_dim}_${variant_name})
  set(SDPA_FUNCTION_NAME ${function_name})
  set(SDPA_TEMPLATE_NAME launch_${mode}_kernel_${head_dim})
  set(SDPA_CAUSAL ${causal_value})
  set(SDPA_HAS_MASK ${has_mask_value})
  set(SDPA_IS_VARLEN ${is_varlen_value})
  set(SDPA_ELEMENT_TYPE ${dtype_type})
  string(APPEND SDPA_KERNEL_DECLARATIONS "int ${function_name}(Options const& options);\n")
  set(SDPA_KERNEL_DECLARATIONS ${SDPA_KERNEL_DECLARATIONS} PARENT_SCOPE)
  set(_generated_src
    ${CMAKE_CURRENT_BINARY_DIR}/generated/sdpa/${mode}_${dtype_name}_${head_dim}_${variant_name}.cpp)
  configure_file(${CMAKE_CURRENT_LIST_DIR}/sdpa_kernel_instantiation.cpp.in ${_generated_src} @ONLY)
  list(APPEND SDPA_GENERATED_SRCS ${_generated_src})
  set(SDPA_GENERATED_SRCS ${SDPA_GENERATED_SRCS} PARENT_SCOPE)
endfunction()

foreach(mode IN ITEMS prefill decode)
  foreach(dtype_name IN ITEMS f16 bf16)
    if(dtype_name STREQUAL "f16")
      set(dtype_type "cute::half_t")
    else()
      set(dtype_type "cute::bfloat16_t")
    endif()

    foreach(head_dim IN ITEMS 128 64 96 192)
      foreach(varlen_name IN ITEMS normal varlen)
        if(varlen_name STREQUAL "varlen")
          if(mode STREQUAL "decode")
            continue()
          endif()
          set(is_varlen_value true)
          set(varlen_suffix "_varlen")
        else()
          set(is_varlen_value false)
          set(varlen_suffix "")
        endif()

        foreach(causal_name IN ITEMS causal noncausal)
          if(causal_name STREQUAL "causal")
            set(causal_value true)
            set(mask_names unmasked)
          else()
            set(causal_value false)
            set(mask_names masked unmasked)
          endif()

          foreach(mask_name IN LISTS mask_names)
            if(mask_name STREQUAL "masked")
              set(has_mask_value true)
            else()
              set(has_mask_value false)
            endif()

            set(variant_name ${causal_name})
            if(causal_name STREQUAL "noncausal")
              set(variant_name noncausal_${mask_name})
            endif()
            string(APPEND variant_name ${varlen_suffix})
            generate_sdpa_instantiation(${mode} ${dtype_name} "${dtype_type}" ${head_dim} ${variant_name}
                                         ${causal_value} ${has_mask_value} ${is_varlen_value})
          endforeach()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()

configure_file(${CMAKE_CURRENT_LIST_DIR}/sdpa_kernel_declarations.hpp.in ${SDPA_DECLARATIONS_FILE} @ONLY)