python3 main.py \
--model_name  google/gemma-7b \
--device 0 \
--group_size 128 \
--bits 4 \
--iters 1000 \
--minmax_lr 2e-3 \
--deployment_device 'gpu' \
--model_dtype "float16" \
--disable_low_gpu_mem_usage \
--output_dir "./tmp_autoround"