python3 main.py \
--model_name  mistralai/Mixtral-8x7B-v0.1 \
--device 0 \
--group_size 128 \
--bits 4 \
--iters 1000 \
--enable_minmax_tuning \
--low_gpu_mem_usage \
--deployment_device 'gpu' \
--scale_dtype 'fp32' \
--eval_bs 32 \
--output_dir "./tmp_autoround" \
--amp