trigger:
  branches:
    include:
      - main
  paths:
    include:
      - auto_round_extension/ark/**
      - .azure-pipelines/build-auto-round-lib.yml
      - .azure-pipelines/template/lib-build-template.yml
    exclude:
      - "*.md"
      - "**/*.md"

stages:
  - template: template/lib-build-template.yml
    parameters:
      publishToTestPyPI: true
