trigger: none

variables:
  - name: POOL_NAME
    value: "RunPod-GPU-Pool"
  - name: AGENT_NAME
    value: "runpod-agent-$(Build.BuildId)"

stages:
  - template: template/cuda-stages-template.yml
    parameters:
      matrix:
        part1:
          PART: 1
        part2:
          PART: 2
        part3:
          PART: 3
